### ISSUE TITLE
Exceptions crash application even in try catch block (mm + func:(id)object + arc)

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#71] opened 2019-03-26 09:57 UTC
Exceptions crash application even in try catch block. It always happen in case of voodoo magic combo: 
source.mm (compiled with clang++) + exception thrown inside function with object argument + used -fobjc-arc.
Important note: crashed only on Windows with msys or my toolchain. MacOS or Linux work fine.

Example code:
```
-(void)testException {
    @throw @"Exception raised";
}

-(void)testException2:(int)option {
    @throw @"Exception raised";
}

-(void)testException3:(OFString*)exception {
    @throw exception;
}

-(void)testException4:(id)option {
    @throw @"Exception raised";
}

-(void)applicationDidFinishLaunching {
    @try {
        //@throw @"Exception raised"; // work fine
        //[self testException]; // work fine
        //[self testException2:0]; // work fine
        
        [self testException3:@"Exception raised"]; // crash
        //[self testException4:nil]; // crash
    } @catch (id exception) {
        of_log(@"%@", exception);
    }
}
```

**Comment by Midar** [comment] 2019-03-29 09:43
It is a known compiler bug on Windows and there’s not much I can do about it, it seems. This is a duplicate of #46, which contains some analysis.

**Comment by winnydows** [comment] 2019-03-30 12:26
It look a similar, but it's another bug. Probaly in findCallsite function of exceptions.m.

Proper catch:
```
C:\Users\winny>C:\Users\winny\Desktop\test_proper.exe
DEBUG: OF_CONSTRUCTOR
DEBUG: of_spinlock_new 0
DEBUG: objc_setUncaughtExceptionHandler
DEBUG: runloop 0
DEBUG: runloop 1
DEBUG: runloop 2
DEBUG: runloop end
DEBUG: objc_exception_throw 0
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: PERSONALITY_FUNC 0
DEBUG: readLSDA 0
DEBUG: getBase 0
DEBUG: findCallsite 0
DEBUG: findCallsite 1
DEBUG: findCallsite 2
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200355
DEBUG: readValue 0
DEBUG: callsiteLength 49
DEBUG: readValue 0
DEBUG: callsiteLandingpad 158
DEBUG: callsiteAction 1
DEBUG: findCallsite return true
DEBUG: findActionRecord 0
DEBUG: sizeForEncoding 0
DEBUG: readValue 0
DEBUG: sizeForEncoding 0
DEBUG: classMatches 0
DEBUG: PERSONALITY_FUNC 0
DEBUG: _Unwind_Reason_Code 0
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
Exception catched
applicationDidFinishLaunching completed 
```

Crashed (with fix when ex == NULL, for avoiding endless crash loop):
```
DEBUG: OF_CONSTRUCTOR
DEBUG: of_spinlock_new 0
DEBUG: objc_setUncaughtExceptionHandler
DEBUG: runloop 0
DEBUG: runloop 1
DEBUG: runloop 2
DEBUG: runloop end
DEBUG: objc_exception_throw 0
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: PERSONALITY_FUNC 0
DEBUG: readLSDA 0
DEBUG: getBase 0
DEBUG: findCallsite 0
DEBUG: findCallsite 1
DEBUG: findCallsite 2
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200224
DEBUG: readValue 0
DEBUG: callsiteLength 48
DEBUG: readValue 0
DEBUG: callsiteLandingpad 0
DEBUG: callsiteAction 0
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200272
DEBUG: readValue 0
DEBUG: callsiteLength 8
DEBUG: readValue 0
DEBUG: callsiteLandingpad 63
DEBUG: callsiteAction 0
DEBUG: findCallsite return true
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: PERSONALITY_FUNC 0
DEBUG: readLSDA 0
DEBUG: getBase 0
DEBUG: findCallsite 0
DEBUG: findCallsite 1
DEBUG: findCallsite 2
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200355
DEBUG: readValue 0
DEBUG: callsiteLength 52
DEBUG: readValue 0
DEBUG: callsiteLandingpad 161
DEBUG: callsiteAction 1
DEBUG: findCallsite return true
DEBUG: findActionRecord 0
DEBUG: sizeForEncoding 0
DEBUG: readValue 0
DEBUG: sizeForEncoding 0
DEBUG: classMatches 0
DEBUG: PERSONALITY_FUNC 0
DEBUG: _Unwind_Reason_Code 0
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: PERSONALITY_FUNC 0
DEBUG: readLSDA 0
DEBUG: getBase 0
DEBUG: findCallsite 0
DEBUG: findCallsite 1
DEBUG: findCallsite 2
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200224
DEBUG: readValue 0
DEBUG: callsiteLength 48
DEBUG: readValue 0
DEBUG: callsiteLandingpad 0
DEBUG: callsiteAction 0
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200272
DEBUG: readValue 0
DEBUG: callsiteLength 8
DEBUG: readValue 0
DEBUG: callsiteLandingpad 63
DEBUG: callsiteAction 0
DEBUG: findCallsite return true
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: PERSONALITY_FUNC 0
DEBUG: readLSDA 0
DEBUG: getBase 0
DEBUG: findCallsite 0
DEBUG: findCallsite 1
DEBUG: findCallsite 2
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200224
DEBUG: readValue 0
DEBUG: callsiteLength 48
DEBUG: readValue 0
DEBUG: callsiteLandingpad 0
DEBUG: callsiteAction 0
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200272
DEBUG: readValue 0
DEBUG: callsiteLength 8
DEBUG: readValue 0
DEBUG: callsiteLandingpad 63
DEBUG: callsiteAction 0
DEBUG: findCallsite while start
DEBUG: readValue 0
DEBUG: callsiteStart 4200280
DEBUG: readValue 0
DEBUG: callsiteLength 48
DEBUG: readValue 0
DEBUG: callsiteLandingpad 0
DEBUG: callsiteAction 0
DEBUG: findCallsite return true
DEBUG: 0
DEBUG: ex->class 5138137972457228867
DEBUG: 1
DEBUG: 2
DEBUG: 0
DEBUG: ex == NULL !!!
DEBUG: 1
DEBUG: 2
DEBUG: 0
DEBUG: ex == NULL !!!
DEBUG: 1
DEBUG: 2
```

**Comment by winnydows** [comment] 2019-03-30 12:29
First listing for case -(void)testException2:(int)option, called with 0.
Crash listing for -(void)testException4:(id)option, called with nil.

Marked source:
```
static bool
findCallsite(struct _Unwind_Context *ctx, struct lsda *LSDA,
    uintptr_t *landingpad, const uint8_t **actionRecords)
{
    printf("DEBUG: findCallsite 0\n");
	uintptr_t IP = _Unwind_GetIP(ctx);
    printf("DEBUG: findCallsite 1\n");
	const uint8_t *ptr = LSDA->callsites;
    printf("DEBUG: findCallsite 2\n");

	*landingpad = 0;
	*actionRecords = NULL;

#ifndef HAVE_SJLJ_EXCEPTIONS
	while (ptr < LSDA->actionTable) {
		uintptr_t callsiteStart, callsiteLength, callsiteLandingpad;
		uintptr_t callsiteAction;

        printf("DEBUG: findCallsite while start\n");
		callsiteStart = LSDA->regionStart +
		    (uintptr_t)readValue(LSDA->callsitesEnc, &ptr);
        printf("DEBUG: callsiteStart %lld\n", callsiteStart);
		callsiteLength = (uintptr_t)readValue(LSDA->callsitesEnc, &ptr);
        printf("DEBUG: callsiteLength %lld\n", callsiteLength);
		callsiteLandingpad =
		    (uintptr_t)readValue(LSDA->callsitesEnc, &ptr);
        printf("DEBUG: callsiteLandingpad %lld\n", callsiteLandingpad);
		callsiteAction = (uintptr_t)readULEB128(&ptr);
        printf("DEBUG: callsiteAction %lld\n", callsiteAction);
        
		/* We can stop if we passed IP, as the table is sorted */
        if (callsiteStart >= IP) {
            printf("DEBUG: findCallsite break\n");
			break;
        }

		if (callsiteStart + callsiteLength >= IP) {
			if (callsiteLandingpad != 0)
				*landingpad = LSDA->landingpadsStart +
				    callsiteLandingpad;
			if (callsiteAction != 0)
				*actionRecords = LSDA->actionTable +
				    callsiteAction - 1;

            printf("DEBUG: findCallsite return true\n");
			return true;
		}
	}

    printf("DEBUG: findCallsite return false\n");
	return false;
```

Will try research problem.

**Comment by winnydows** [comment] 2019-03-30 13:10
Dump without arc (don't crash with object argument):

```
C:\Users\winny>C:\Users\winny\Desktop\test_noarc.exe
DEBUG: objc_setUncaughtExceptionHandler
DEBUG: objc_exception_throw 0
DEBUG: __gnu_objc_personality_seh0
DEBUG: _GCC_specific_handler
DEBUG: PERSONALITY_FUNC 0
DEBUG: readLSDA
DEBUG: getBase 0
DEBUG: readLSDA callsitesSize 10
DEBUG: findCallsite
DEBUG: findCallsite while start
DEBUG: readValue 1
DEBUG: callsiteStart 4200195
DEBUG: readValue 1
DEBUG: callsiteLength 52
DEBUG: readValue 1
DEBUG: callsiteLandingpad 161
DEBUG: callsiteAction 1
DEBUG: findCallsite return true
DEBUG: findActionRecord 0
DEBUG: sizeForEncoding 0
DEBUG: readValue 0
DEBUG: sizeForEncoding 0
DEBUG: classMatches 0
DEBUG: PERSONALITY_FUNC 0
DEBUG: _Unwind_Reason_Code 0
DEBUG: __gnu_objc_personality_seh0
DEBUG: _GCC_specific_handler
Exception catched
applicationDidFinishLaunching completed
```

**Comment by winnydows** [comment] 2019-03-30 13:42
callsiteLandingpad =
		    (uintptr_t)readValue(LSDA->callsitesEnc, &ptr); read 0, when must be value.

**Comment by winnydows** [comment] 2019-03-30 13:49
getBase on beginning also different - crashed test getBase 255 and all proper getBase 0.

**Comment by Midar** [comment] 2019-04-02 22:44
Can you try the same with the GNU or GNUstep runtime? I think the tables generated by Clang on Win64 are faulty.

**Comment by Midar** [comment] 2020-06-07 14:41
Ping - I'd still be interested in a comparison with other runtimes, to see whether this is a compiler bug or a runtime bug.

**Comment by Midar** [comment] 2020-06-07 14:41
Similar issue on Fossil: https://objfw.nil.im/tktview?name=ced9d8df0b

Feel free to update there.

**Comment by Midar** [comment] 2020-09-08 12:46
Closing due to no feedback.

**Closed by Midar** 2020-09-08 12:46 UTC
Labels: windows
